import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Notification from "@/app/components/Notification";
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";
import AuthProvider from "./components/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DeliverIt ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-primary-primary1 text-text-text1`}>
        <AuthProvider>
          <div>
      <Notification/>
      <Navbar/>
      {children}
      <Footer/>
      </div>
      </AuthProvider>
      </body>
    </html>
  );
}
